# Generated by Django 5.2.9 on 2025-12-11 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0003_remove_carmodel_dealer_id_remove_carmodel_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                ("zip_code", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="carmodel",
            name="type",
            field=models.CharField(
                choices=[("SEDAN", "Sedan"), ("SUV", "SUV"), ("WAGON", "Wagon")],
                default="SUV",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2015),
                    django.core.validators.MaxValueValidator(2023),
                ]
            ),
        ),
    ]
